name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        sci: ["before", "suffix"]  # package no longer available on my channel
        pysrc: ["conda"]
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    
    - 
      if: ${{ matrix.pysrc == 'system' }}
      name: Set up Python ${{ matrix.python-version }} from system
      uses: actions/setup-python@v4.2.0
      with:
        python-version: ${{ matrix.python-version }}

    -
      if: ${{ matrix.pysrc == 'conda' }} 
      name: Set up Python ${{ matrix.python-version }} from conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge
        auto-activate-base: false
        activate-environment: test
        auto-update-conda: true
        channel-priority: strict

    -
      name: Install deps
      run: |
        if [[ ${{ matrix.pysrc }} == "conda" && ${{ matrix.sci }} == "fortran" ]]; then
          mamba update --all --yes
          mamba install pytest scipy openblas -c ngam --yes
          mamba clean -aqy
          mamba list
        elif [[ ${{ matrix.pysrc }} == "conda" && ${{ matrix.sci }} == "suffix" ]]; then
          mamba update --all --yes
          mamba install pytest scipy openblas --yes
          mamba clean -aqy
          mamba list
        elif [[ ${{ matrix.pysrc }} == "conda" && ${{ matrix.sci }} == "before" ]]; then
          mamba update --all --yes
          mamba install pytest scipy 'openblas==*=*_2*' --yes
          mamba clean -aqy
          mamba list
        else
          python -m pip install -U pip
          python -m pip install ".[test]"
        fi

    -
      name: Test with pytest
      run: |
        pytest --pyargs scipy.linalg.tests.test_decomp_update
        pytest --pyargs scipy.linalg.tests.test_lapack
